use crate::timing::{ICMP_DGRAM_SESSION_QUIET_WAIT, TEST_POLL_INTERVAL};

use sha2::{Digest, Sha256};
use std::collections::VecDeque;
use std::fmt;
use std::fmt::Write as _;
use std::fs::{File, OpenOptions, TryLockError as FileTryLockError};
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};
use std::sync::{Condvar, Mutex};
use std::thread;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

// RAW sockets observe ICMP traffic generated by ping DGRAM sockets too, so all
// ICMP wire tests must share one serialization domain. Separate locks allow a
// kernel-echo test to inject packets while a RAW admission test is running.
static ICMP_WIRE_LOCK: ProcessIcmpLock = ProcessIcmpLock::new();

struct ProcessIcmpLock {
    state: Mutex<ProcessIcmpLockState>,
    changed: Condvar,
}

struct ProcessIcmpLockState {
    next_ticket: u64,
    waiting: VecDeque<u64>,
    held: bool,
}

struct ProcessIcmpGuard {
    lock: &'static ProcessIcmpLock,
}

pub struct RawIcmpGuard {
    process_guard: Option<ProcessIcmpGuard>,
    file: File,
    release_quiet: Duration,
}

#[derive(Debug)]
pub struct RawIcmpLockError {
    pub test_name: &'static str,
    pub path: PathBuf,
    pub waited: std::time::Duration,
    pub holder: Option<String>,
    pub source: Option<io::Error>,
}

impl fmt::Display for RawIcmpLockError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "ICMP wire lock for {} was unavailable after {:?}: {}",
            self.test_name,
            self.waited,
            self.path.display()
        )?;
        if let Some(holder) = &self.holder {
            write!(formatter, "\nlast holder metadata: {}", holder.trim())?;
        }
        if let Some(source) = &self.source {
            write!(formatter, "\nlock error: {source}")?;
        }
        Ok(())
    }
}

impl std::error::Error for RawIcmpLockError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.source
            .as_ref()
            .map(|source| source as &(dyn std::error::Error + 'static))
    }
}

pub fn acquire_raw_icmp_lock(
    deadline: Instant,
    test_name: &'static str,
) -> Result<RawIcmpGuard, RawIcmpLockError> {
    acquire_icmp_lock(deadline, test_name, "wire-integration", &ICMP_WIRE_LOCK)
}

pub fn acquire_icmp_dgram_session_lock(
    deadline: Instant,
    test_name: &'static str,
) -> Result<RawIcmpGuard, RawIcmpLockError> {
    let mut guard = acquire_icmp_lock(deadline, test_name, "wire-integration", &ICMP_WIRE_LOCK)?;
    guard.release_quiet = ICMP_DGRAM_SESSION_QUIET_WAIT;
    Ok(guard)
}

fn acquire_icmp_lock(
    deadline: Instant,
    test_name: &'static str,
    scope: &str,
    process_lock: &'static ProcessIcmpLock,
) -> Result<RawIcmpGuard, RawIcmpLockError> {
    let started = Instant::now();
    let process_guard = process_lock
        .acquire(deadline)
        .ok_or_else(|| lock_error(test_name, icmp_lock_path(scope), started.elapsed(), None))?;

    let path = icmp_lock_path(scope);
    let file = OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .truncate(false)
        .open(&path)
        .map_err(|source| lock_error(test_name, path.clone(), started.elapsed(), Some(source)))?;

    loop {
        match file.try_lock() {
            Ok(()) => {
                write_holder_metadata(&path, test_name).map_err(|source| {
                    lock_error(test_name, path.clone(), started.elapsed(), Some(source))
                })?;
                return Ok(RawIcmpGuard {
                    process_guard: Some(process_guard),
                    file,
                    release_quiet: Duration::ZERO,
                });
            }
            Err(FileTryLockError::WouldBlock) if Instant::now() < deadline => {
                thread::sleep(
                    TEST_POLL_INTERVAL.min(deadline.saturating_duration_since(Instant::now())),
                );
            }
            Err(FileTryLockError::WouldBlock) => {
                return Err(RawIcmpLockError {
                    test_name,
                    path: path.clone(),
                    waited: started.elapsed(),
                    holder: read_holder_metadata(&path),
                    source: None,
                });
            }
            Err(FileTryLockError::Error(source)) => {
                return Err(lock_error(
                    test_name,
                    path.clone(),
                    started.elapsed(),
                    Some(source),
                ));
            }
        }
    }
}

impl ProcessIcmpLock {
    const fn new() -> Self {
        Self {
            state: Mutex::new(ProcessIcmpLockState {
                next_ticket: 0,
                waiting: VecDeque::new(),
                held: false,
            }),
            changed: Condvar::new(),
        }
    }

    fn acquire(&'static self, deadline: Instant) -> Option<ProcessIcmpGuard> {
        let mut state = self.state.lock().unwrap_or_else(|error| error.into_inner());
        let ticket = state.next_ticket;
        state.next_ticket = state.next_ticket.wrapping_add(1);
        state.waiting.push_back(ticket);

        loop {
            if !state.held && state.waiting.front() == Some(&ticket) {
                state.waiting.pop_front();
                state.held = true;
                return Some(ProcessIcmpGuard { lock: self });
            }

            let remaining = deadline.saturating_duration_since(Instant::now());
            if remaining.is_zero() {
                state.waiting.retain(|waiting| *waiting != ticket);
                self.changed.notify_all();
                return None;
            }
            let (next_state, _) = self
                .changed
                .wait_timeout(state, TEST_POLL_INTERVAL.min(remaining))
                .unwrap_or_else(|error| error.into_inner());
            state = next_state;
        }
    }

    #[cfg(test)]
    fn waiting_count(&self) -> usize {
        self.state
            .lock()
            .unwrap_or_else(|error| error.into_inner())
            .waiting
            .len()
    }
}

impl Drop for ProcessIcmpGuard {
    fn drop(&mut self) {
        let mut state = self
            .lock
            .state
            .lock()
            .unwrap_or_else(|error| error.into_inner());
        state.held = false;
        self.lock.changed.notify_all();
    }
}

impl Drop for RawIcmpGuard {
    fn drop(&mut self) {
        if !self.release_quiet.is_zero() {
            thread::sleep(self.release_quiet);
        }
        if let Err(error) = self.file.unlock() {
            eprintln!("unlock RAW ICMP integration file: {error}");
        }
        drop(self.process_guard.take());
        if !self.release_quiet.is_zero() {
            thread::sleep(TEST_POLL_INTERVAL);
        }
    }
}

fn icmp_lock_path(scope: &str) -> PathBuf {
    let repository = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .unwrap_or_else(|_| Path::new(env!("CARGO_MANIFEST_DIR")).join("../.."));
    let user_scope = current_user_scope();
    let mut digest = Sha256::new();
    digest.update(repository.to_string_lossy().as_bytes());
    digest.update(b"\0");
    digest.update(user_scope.as_bytes());
    digest.update(b"\0");
    digest.update(scope.as_bytes());
    let finalized = digest.finalize();
    let mut hash = String::with_capacity(finalized.len() * 2);
    for byte in finalized {
        write!(hash, "{byte:02x}").expect("writing to String cannot fail");
    }
    std::env::temp_dir().join(format!("pkthere-raw-icmp-{}.lock", &hash[..16]))
}

#[cfg(unix)]
fn current_user_scope() -> String {
    nix::unistd::geteuid().as_raw().to_string()
}

#[cfg(windows)]
fn current_user_scope() -> String {
    format!(
        "{}:{}",
        std::env::var_os("USERNAME")
            .unwrap_or_default()
            .to_string_lossy(),
        std::env::temp_dir().to_string_lossy()
    )
}

#[cfg(not(any(unix, windows)))]
fn current_user_scope() -> String {
    std::env::temp_dir().to_string_lossy().into_owned()
}

fn holder_metadata_path(lock_path: &Path) -> PathBuf {
    // Windows may deny reopening an exclusively locked file even for reading.
    // Keep diagnostics beside the authoritative OS lock so waiters can always
    // identify the holder without weakening the lock mode.
    let mut file_name = lock_path.file_name().unwrap_or_default().to_os_string();
    file_name.push(".holder");
    lock_path.with_file_name(file_name)
}

fn write_holder_metadata(lock_path: &Path, test_name: &str) -> io::Result<()> {
    let acquired = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let mut file = OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .open(holder_metadata_path(lock_path))?;
    writeln!(
        file,
        "pid={} test={} acquired_unix_s={acquired}",
        std::process::id(),
        test_name
    )?;
    file.flush()
}

fn read_holder_metadata(path: &Path) -> Option<String> {
    [holder_metadata_path(path), path.to_path_buf()]
        .into_iter()
        .find_map(|candidate| {
            let mut metadata = String::new();
            File::open(candidate)
                .ok()?
                .read_to_string(&mut metadata)
                .ok()?;
            (!metadata.trim().is_empty()).then_some(metadata)
        })
}

fn lock_error(
    test_name: &'static str,
    path: PathBuf,
    waited: std::time::Duration,
    source: Option<io::Error>,
) -> RawIcmpLockError {
    RawIcmpLockError {
        test_name,
        holder: read_holder_metadata(&path),
        path,
        waited,
        source,
    }
}

#[cfg(test)]
mod tests {
    use super::{
        ProcessIcmpLock, acquire_icmp_dgram_session_lock, acquire_raw_icmp_lock, icmp_lock_path,
    };
    use crate::timing::{RAW_ICMP_LOCK_WAIT, TEST_POLL_INTERVAL};
    use std::sync::mpsc;
    use std::thread;
    use std::time::Instant;

    static FAIRNESS_TEST_LOCK: ProcessIcmpLock = ProcessIcmpLock::new();

    #[test]
    fn raw_lock_path_is_scoped_and_lock_is_reacquirable() {
        let path = icmp_lock_path("wire-integration");
        assert!(
            path.file_name()
                .expect("lock filename")
                .to_string_lossy()
                .starts_with("pkthere-raw-icmp-")
        );
        let guard = acquire_raw_icmp_lock(
            Instant::now() + RAW_ICMP_LOCK_WAIT,
            "raw_lock_path_is_scoped_and_lock_is_reacquirable",
        )
        .expect("first RAW lock");
        drop(guard);
        acquire_raw_icmp_lock(
            Instant::now() + RAW_ICMP_LOCK_WAIT,
            "raw_lock_path_is_scoped_and_lock_is_reacquirable",
        )
        .expect("reacquired RAW lock");
    }

    #[test]
    fn raw_and_dgram_tests_share_one_icmp_wire_lock() {
        let raw_guard = acquire_raw_icmp_lock(
            Instant::now() + RAW_ICMP_LOCK_WAIT,
            "raw_and_dgram_tests_share_one_icmp_wire_lock_raw",
        )
        .expect("acquire RAW ICMP wire lock");
        let dgram_error = match acquire_icmp_dgram_session_lock(
            Instant::now() + TEST_POLL_INTERVAL,
            "raw_and_dgram_tests_share_one_icmp_wire_lock_dgram",
        ) {
            Ok(_) => panic!("ICMP DGRAM lock bypassed active RAW wire lock"),
            Err(error) => error,
        };
        assert_eq!(
            dgram_error.path,
            icmp_lock_path("wire-integration"),
            "RAW and DGRAM lock attempts must use the same OS lock file"
        );
        drop(raw_guard);
        acquire_icmp_dgram_session_lock(
            Instant::now() + RAW_ICMP_LOCK_WAIT,
            "raw_and_dgram_tests_share_one_icmp_wire_lock_reacquire",
        )
        .expect("acquire DGRAM lock after RAW guard release");
    }

    #[test]
    fn process_lock_serves_waiters_in_arrival_order() {
        let first = FAIRNESS_TEST_LOCK
            .acquire(Instant::now() + RAW_ICMP_LOCK_WAIT)
            .expect("first process lock");
        let (sender, receiver) = mpsc::channel();

        let sender_b = sender.clone();
        let waiter_b = thread::spawn(move || {
            let _guard = FAIRNESS_TEST_LOCK
                .acquire(Instant::now() + RAW_ICMP_LOCK_WAIT)
                .expect("second process lock");
            sender_b.send('b').expect("report second waiter");
        });
        wait_for_waiter_count(1);

        let waiter_c = thread::spawn(move || {
            let _guard = FAIRNESS_TEST_LOCK
                .acquire(Instant::now() + RAW_ICMP_LOCK_WAIT)
                .expect("third process lock");
            sender.send('c').expect("report third waiter");
        });
        wait_for_waiter_count(2);

        drop(first);
        assert_eq!(
            receiver
                .recv_timeout(RAW_ICMP_LOCK_WAIT)
                .expect("first queued waiter result"),
            'b'
        );
        assert_eq!(
            receiver
                .recv_timeout(RAW_ICMP_LOCK_WAIT)
                .expect("second queued waiter result"),
            'c'
        );
        waiter_b.join().expect("join second waiter");
        waiter_c.join().expect("join third waiter");
    }

    fn wait_for_waiter_count(expected: usize) {
        let deadline = Instant::now() + RAW_ICMP_LOCK_WAIT;
        while FAIRNESS_TEST_LOCK.waiting_count() < expected {
            assert!(
                Instant::now() < deadline,
                "process lock did not enqueue {expected} waiter(s)"
            );
            thread::sleep(TEST_POLL_INTERVAL);
        }
    }
}
