//! Static synchronization-authority catalogs.

use super::{
    AuthorityDomain, AuthorityId, AuthorityRecord, BlockingEdge, CoholdRule, FunctionIdentity,
    InvariantId, OwnershipModel, PublicationId, PublicationRecord, TypeIdentity, WaitId,
    WaitProtocolRecord, WaitRecord,
};

mod operations;
pub(crate) use operations::{OPERATION_RECORDS, OPERATION_REQUIREMENTS, SHARED_RMW_RECORDS};
mod atomics;
pub(crate) use atomics::ATOMIC_PROTOCOL_RECORDS;
mod blocking;
pub(crate) use blocking::BLOCKING_CONTRACTS;
mod lifecycles;
pub(crate) use lifecycles::LIFECYCLE_OWNERSHIP_RECORDS;
mod refcounts;
pub(crate) use refcounts::REFERENCE_COUNT_OWNERSHIP_RECORDS;
mod evidence;
pub(crate) use evidence::NEGATIVE_CONTROL_EXPECTATIONS;

pub(crate) const AUTHORITY_RECORDS: &[AuthorityRecord] = &[
    AuthorityRecord {
        id: AuthorityId::FlowRead,
        domain: AuthorityDomain::Flow,
        blocking: false,
        hot_path: true,
        directional: false,
        owner: OwnershipModel::Lane,
        instance_rule: "one registered worker lane per logical flow",
        invalidation: "flow publication epoch",
        publication: "flow gate epoch publishes immutable snapshot",
    },
    AuthorityRecord {
        id: AuthorityId::FlowReservation,
        domain: AuthorityDomain::Flow,
        blocking: true,
        hot_path: false,
        directional: false,
        owner: OwnershipModel::FifoReservation,
        instance_rule: "one FIFO reservation queue per logical flow",
        invalidation: "flow reservation ticket",
        publication: "reservation orders writers before flow-gate closure",
    },
    AuthorityRecord {
        id: AuthorityId::FlowClaim,
        domain: AuthorityDomain::Flow,
        blocking: true,
        hot_path: false,
        directional: false,
        owner: OwnershipModel::Mutex,
        instance_rule: "one process-wide map assigning each single-flow tuple to one worker pair",
        invalidation: "flow claim insertion or release",
        publication: "claim ownership is visible before client-flow topology publication",
    },
    AuthorityRecord {
        id: AuthorityId::FlowWrite,
        domain: AuthorityDomain::Flow,
        blocking: true,
        hot_path: false,
        directional: false,
        owner: OwnershipModel::FifoReservation,
        instance_rule: "one FIFO writer per logical flow",
        invalidation: "flow publication epoch",
        publication: "writer reopens flow gate at a fresh epoch",
    },
    AuthorityRecord {
        id: AuthorityId::ManagerTransaction,
        domain: AuthorityDomain::Manager,
        blocking: true,
        hot_path: false,
        directional: false,
        owner: OwnershipModel::FifoReservation,
        instance_rule: "socket slots acquired in ascending slot order",
        invalidation: "manager transaction token",
        publication: "manager versions publish only after complete transaction preparation",
    },
    AuthorityRecord {
        id: AuthorityId::ManagerState,
        domain: AuthorityDomain::Manager,
        blocking: true,
        hot_path: false,
        directional: false,
        owner: OwnershipModel::Mutex,
        instance_rule: "socket slots acquired in ascending slot order",
        invalidation: "manager StateVersion",
        publication: "StateVersion changes only with committed manager state",
    },
    AuthorityRecord {
        id: AuthorityId::SocketTopology,
        domain: AuthorityDomain::Socket,
        blocking: true,
        hot_path: false,
        directional: false,
        owner: OwnershipModel::FifoReservation,
        instance_rule: "socket slots acquired in ascending slot order",
        invalidation: "socket topology epoch",
        publication: "socket gate reopens only after descriptor and receiver publication",
    },
    AuthorityRecord {
        id: AuthorityId::SocketAssociation,
        domain: AuthorityDomain::Socket,
        blocking: true,
        hot_path: false,
        directional: false,
        owner: OwnershipModel::Mutex,
        instance_rule: "association and required-bind instances use ascending kind order",
        invalidation: "socket association epoch",
        publication: "association changes only while the topology gate is closed",
    },
    AuthorityRecord {
        id: AuthorityId::SocketDescriptor,
        domain: AuthorityDomain::Socket,
        blocking: true,
        hot_path: false,
        directional: false,
        owner: OwnershipModel::Mutex,
        instance_rule: "one persistent descriptor owner per socket slot",
        invalidation: "descriptor generation",
        publication: "descriptor ownership changes only through topology publication",
    },
    AuthorityRecord {
        id: AuthorityId::SocketIo,
        domain: AuthorityDomain::Socket,
        blocking: false,
        hot_path: true,
        directional: true,
        owner: OwnershipModel::Lane,
        instance_rule: "one direction-local lane per worker and socket",
        invalidation: "socket topology epoch",
        publication: "lane is valid only for the identical open topology epoch",
    },
    AuthorityRecord {
        id: AuthorityId::ControlObservation,
        domain: AuthorityDomain::Protocol,
        blocking: false,
        hot_path: true,
        directional: true,
        owner: OwnershipModel::SingleWriter,
        instance_rule: "one observation lane per worker direction",
        invalidation: "observation generation",
        publication: "observed control identity publishes after successful receive",
    },
    AuthorityRecord {
        id: AuthorityId::ProtocolTransmit,
        domain: AuthorityDomain::Protocol,
        blocking: false,
        hot_path: true,
        directional: true,
        owner: OwnershipModel::SingleWriter,
        instance_rule: "at most one transmit session instance held by a stable packet",
        invalidation: "session status and sequence generation",
        publication: "send-completion CAS owns reservation evidence deferred control outcome and retirement",
    },
    AuthorityRecord {
        id: AuthorityId::ProtocolReceive,
        domain: AuthorityDomain::Protocol,
        blocking: true,
        hot_path: true,
        directional: true,
        owner: OwnershipModel::Mutex,
        instance_rule: "at most one same-direction receive session held",
        invalidation: "receive session generation",
        publication: "replay mutation is visible before receive authority releases",
    },
    AuthorityRecord {
        id: AuthorityId::ResetBudget,
        domain: AuthorityDomain::Protocol,
        blocking: true,
        hot_path: false,
        directional: false,
        owner: OwnershipModel::Mutex,
        instance_rule: "one process-wide hostile-response budget",
        invalidation: "token-bucket refill epoch",
        publication: "global budget reservation precedes per-flow budget reservation",
    },
    AuthorityRecord {
        id: AuthorityId::SessionControl,
        domain: AuthorityDomain::Protocol,
        blocking: true,
        hot_path: false,
        directional: true,
        owner: OwnershipModel::Mutex,
        instance_rule: "candidate batches use flow-direction-kind-session order",
        invalidation: "flow/session epoch",
        publication: "session controls publish through the flow writer",
    },
    AuthorityRecord {
        id: AuthorityId::Activity,
        domain: AuthorityDomain::Flow,
        blocking: false,
        hot_path: true,
        directional: true,
        owner: OwnershipModel::SingleWriter,
        instance_rule: "one activity lane per worker direction",
        invalidation: "flow activity generation",
        publication: "seqlock publication keeps epoch and tick coherent; it does not authorize timeout commit",
    },
    AuthorityRecord {
        id: AuthorityId::Maintenance,
        domain: AuthorityDomain::Runtime,
        blocking: true,
        hot_path: false,
        directional: false,
        owner: OwnershipModel::Mutex,
        instance_rule: "one maintenance publication authority per logical flow",
        invalidation: "maintenance epoch",
        publication: "authoritative deadline publishes before its wake",
    },
    AuthorityRecord {
        id: AuthorityId::WakeGeneration,
        domain: AuthorityDomain::Socket,
        blocking: false,
        hot_path: false,
        directional: true,
        owner: OwnershipModel::SingleWriter,
        instance_rule: "one wake owner per worker direction",
        invalidation: "wake generation",
        publication: "pending state uses clear-drain-recheck",
    },
    AuthorityRecord {
        id: AuthorityId::ReceiverClaim,
        domain: AuthorityDomain::Socket,
        blocking: true,
        hot_path: false,
        directional: true,
        owner: OwnershipModel::UniqueClaim,
        instance_rule: "one owner per role, slot, and receiver generation",
        invalidation: "receiver generation",
        publication: "receiver generation follows receiver-slot commit",
    },
    AuthorityRecord {
        id: AuthorityId::WaitCoordination,
        domain: AuthorityDomain::Runtime,
        blocking: true,
        hot_path: false,
        directional: false,
        owner: OwnershipModel::Mutex,
        instance_rule: "one wait coordinator per gate or reservation",
        invalidation: "wait generation or shutdown",
        publication: "wake generation and authoritative predicate are rechecked after wake",
    },
    AuthorityRecord {
        id: AuthorityId::RuntimeSupervisor,
        domain: AuthorityDomain::Runtime,
        blocking: true,
        hot_path: false,
        directional: false,
        owner: OwnershipModel::Mutex,
        instance_rule: "one shutdown controller and one writer per outcome slot",
        invalidation: "shutdown state and outcome generation",
        publication: "cause is ready before fatal state publication",
    },
    AuthorityRecord {
        id: AuthorityId::StatsPublication,
        domain: AuthorityDomain::Stats,
        blocking: false,
        hot_path: false,
        directional: true,
        owner: OwnershipModel::SingleWriter,
        instance_rule: "one producer queue per supervised producer",
        invalidation: "producer lifecycle generation",
        publication: "FIFO marker follows every delta through its sequence",
    },
    AuthorityRecord {
        id: AuthorityId::DiagnosticCounter,
        domain: AuthorityDomain::Diagnostic,
        blocking: false,
        hot_path: false,
        directional: false,
        owner: OwnershipModel::Counter,
        instance_rule: "independent process-wide diagnostic counters",
        invalidation: "process lifetime",
        publication: "checked counters do not publish protocol authority",
    },
    AuthorityRecord {
        id: AuthorityId::Diagnostic,
        domain: AuthorityDomain::Diagnostic,
        blocking: false,
        hot_path: false,
        directional: true,
        owner: OwnershipModel::SingleWriter,
        instance_rule: "one bounded store per worker direction",
        invalidation: "worker lifetime",
        publication: "terminal disposition moves a trace exactly once",
    },
    AuthorityRecord {
        id: AuthorityId::IdentityAllocation,
        domain: AuthorityDomain::Protocol,
        blocking: false,
        hot_path: false,
        directional: false,
        owner: OwnershipModel::Counter,
        instance_rule: "one process-wide checked identity allocator",
        invalidation: "process lifetime",
        publication: "nonzero identities are never reused",
    },
    AuthorityRecord {
        id: AuthorityId::Pacing,
        domain: AuthorityDomain::Protocol,
        blocking: false,
        hot_path: true,
        directional: false,
        owner: OwnershipModel::SingleWriter,
        instance_rule: "one configured cadence pacer",
        invalidation: "last cadence send tick",
        publication: "pacing never gates ordinary user data",
    },
];

/// The edge list is authoritative. Numeric ranks are derived by validation.
pub(crate) const BLOCKING_EDGES: &[BlockingEdge] = &[
    BlockingEdge {
        from: AuthorityId::FlowRead,
        to: AuthorityId::SocketIo,
    },
    BlockingEdge {
        from: AuthorityId::SocketIo,
        to: AuthorityId::ProtocolTransmit,
    },
    BlockingEdge {
        from: AuthorityId::SocketIo,
        to: AuthorityId::ProtocolReceive,
    },
    BlockingEdge {
        from: AuthorityId::ProtocolTransmit,
        to: AuthorityId::SessionControl,
    },
    BlockingEdge {
        from: AuthorityId::SessionControl,
        to: AuthorityId::ProtocolReceive,
    },
    BlockingEdge {
        from: AuthorityId::SessionControl,
        to: AuthorityId::Maintenance,
    },
    BlockingEdge {
        from: AuthorityId::ResetBudget,
        to: AuthorityId::SessionControl,
    },
    BlockingEdge {
        from: AuthorityId::FlowReservation,
        to: AuthorityId::FlowWrite,
    },
    BlockingEdge {
        from: AuthorityId::FlowReservation,
        to: AuthorityId::FlowClaim,
    },
    BlockingEdge {
        from: AuthorityId::FlowWrite,
        to: AuthorityId::FlowClaim,
    },
    BlockingEdge {
        from: AuthorityId::FlowReservation,
        to: AuthorityId::WaitCoordination,
    },
    BlockingEdge {
        from: AuthorityId::FlowWrite,
        to: AuthorityId::ManagerTransaction,
    },
    BlockingEdge {
        from: AuthorityId::ManagerTransaction,
        to: AuthorityId::ManagerState,
    },
    BlockingEdge {
        from: AuthorityId::ManagerTransaction,
        to: AuthorityId::SocketTopology,
    },
    BlockingEdge {
        from: AuthorityId::ManagerTransaction,
        to: AuthorityId::SocketAssociation,
    },
    BlockingEdge {
        from: AuthorityId::SocketTopology,
        to: AuthorityId::SocketAssociation,
    },
    BlockingEdge {
        from: AuthorityId::SocketTopology,
        to: AuthorityId::SocketDescriptor,
    },
    BlockingEdge {
        from: AuthorityId::SocketAssociation,
        to: AuthorityId::SocketDescriptor,
    },
    BlockingEdge {
        from: AuthorityId::SocketAssociation,
        to: AuthorityId::WaitCoordination,
    },
    BlockingEdge {
        from: AuthorityId::SocketTopology,
        to: AuthorityId::SocketIo,
    },
    BlockingEdge {
        from: AuthorityId::SocketTopology,
        to: AuthorityId::ProtocolTransmit,
    },
    BlockingEdge {
        from: AuthorityId::SocketTopology,
        to: AuthorityId::ManagerState,
    },
    BlockingEdge {
        from: AuthorityId::SocketTopology,
        to: AuthorityId::Maintenance,
    },
    BlockingEdge {
        from: AuthorityId::ManagerState,
        to: AuthorityId::ReceiverClaim,
    },
    BlockingEdge {
        from: AuthorityId::ManagerTransaction,
        to: AuthorityId::WaitCoordination,
    },
    BlockingEdge {
        from: AuthorityId::SocketTopology,
        to: AuthorityId::WaitCoordination,
    },
    BlockingEdge {
        from: AuthorityId::FlowWrite,
        to: AuthorityId::WaitCoordination,
    },
    BlockingEdge {
        from: AuthorityId::FlowWrite,
        to: AuthorityId::Maintenance,
    },
];

/// Co-holds are default-deny. Reverse pairs must be listed independently.
pub(crate) const COHOLD_RULES: &[CoholdRule] = &[
    CoholdRule {
        held: AuthorityId::FlowRead,
        acquired: AuthorityId::SocketIo,
    },
    CoholdRule {
        held: AuthorityId::FlowRead,
        acquired: AuthorityId::ProtocolTransmit,
    },
    CoholdRule {
        held: AuthorityId::FlowRead,
        acquired: AuthorityId::ProtocolReceive,
    },
    CoholdRule {
        held: AuthorityId::FlowRead,
        acquired: AuthorityId::SessionControl,
    },
    CoholdRule {
        held: AuthorityId::SocketIo,
        acquired: AuthorityId::ProtocolTransmit,
    },
    CoholdRule {
        held: AuthorityId::SocketIo,
        acquired: AuthorityId::ProtocolReceive,
    },
    CoholdRule {
        held: AuthorityId::SocketIo,
        acquired: AuthorityId::SessionControl,
    },
    CoholdRule {
        held: AuthorityId::ProtocolTransmit,
        acquired: AuthorityId::SessionControl,
    },
    CoholdRule {
        held: AuthorityId::SessionControl,
        acquired: AuthorityId::ProtocolReceive,
    },
    CoholdRule {
        held: AuthorityId::SessionControl,
        acquired: AuthorityId::Maintenance,
    },
    CoholdRule {
        held: AuthorityId::ResetBudget,
        acquired: AuthorityId::SessionControl,
    },
    CoholdRule {
        held: AuthorityId::SessionControl,
        acquired: AuthorityId::SessionControl,
    },
    CoholdRule {
        held: AuthorityId::ProtocolReceive,
        acquired: AuthorityId::ProtocolReceive,
    },
    CoholdRule {
        held: AuthorityId::FlowReservation,
        acquired: AuthorityId::FlowWrite,
    },
    CoholdRule {
        held: AuthorityId::FlowReservation,
        acquired: AuthorityId::FlowClaim,
    },
    CoholdRule {
        held: AuthorityId::FlowWrite,
        acquired: AuthorityId::FlowClaim,
    },
    CoholdRule {
        held: AuthorityId::FlowReservation,
        acquired: AuthorityId::ManagerTransaction,
    },
    CoholdRule {
        held: AuthorityId::FlowReservation,
        acquired: AuthorityId::ManagerState,
    },
    CoholdRule {
        held: AuthorityId::FlowReservation,
        acquired: AuthorityId::SocketTopology,
    },
    CoholdRule {
        held: AuthorityId::FlowReservation,
        acquired: AuthorityId::SocketAssociation,
    },
    CoholdRule {
        held: AuthorityId::FlowReservation,
        acquired: AuthorityId::SocketDescriptor,
    },
    CoholdRule {
        held: AuthorityId::FlowReservation,
        acquired: AuthorityId::SocketIo,
    },
    CoholdRule {
        held: AuthorityId::FlowReservation,
        acquired: AuthorityId::ProtocolTransmit,
    },
    CoholdRule {
        held: AuthorityId::FlowReservation,
        acquired: AuthorityId::SessionControl,
    },
    CoholdRule {
        held: AuthorityId::FlowReservation,
        acquired: AuthorityId::ProtocolReceive,
    },
    CoholdRule {
        held: AuthorityId::FlowReservation,
        acquired: AuthorityId::ReceiverClaim,
    },
    CoholdRule {
        held: AuthorityId::FlowReservation,
        acquired: AuthorityId::WaitCoordination,
    },
    CoholdRule {
        held: AuthorityId::FlowReservation,
        acquired: AuthorityId::Maintenance,
    },
    CoholdRule {
        held: AuthorityId::FlowWrite,
        acquired: AuthorityId::ManagerTransaction,
    },
    CoholdRule {
        held: AuthorityId::FlowWrite,
        acquired: AuthorityId::ManagerState,
    },
    CoholdRule {
        held: AuthorityId::FlowWrite,
        acquired: AuthorityId::SocketTopology,
    },
    CoholdRule {
        held: AuthorityId::FlowWrite,
        acquired: AuthorityId::SocketAssociation,
    },
    CoholdRule {
        held: AuthorityId::FlowWrite,
        acquired: AuthorityId::SocketDescriptor,
    },
    CoholdRule {
        held: AuthorityId::FlowWrite,
        acquired: AuthorityId::SocketIo,
    },
    CoholdRule {
        held: AuthorityId::FlowWrite,
        acquired: AuthorityId::ProtocolTransmit,
    },
    CoholdRule {
        held: AuthorityId::FlowWrite,
        acquired: AuthorityId::SessionControl,
    },
    CoholdRule {
        held: AuthorityId::FlowWrite,
        acquired: AuthorityId::ProtocolReceive,
    },
    CoholdRule {
        held: AuthorityId::FlowWrite,
        acquired: AuthorityId::ReceiverClaim,
    },
    CoholdRule {
        held: AuthorityId::FlowWrite,
        acquired: AuthorityId::WaitCoordination,
    },
    CoholdRule {
        held: AuthorityId::FlowWrite,
        acquired: AuthorityId::Maintenance,
    },
    CoholdRule {
        held: AuthorityId::ManagerTransaction,
        acquired: AuthorityId::ManagerState,
    },
    CoholdRule {
        held: AuthorityId::ManagerTransaction,
        acquired: AuthorityId::ManagerTransaction,
    },
    CoholdRule {
        held: AuthorityId::ManagerTransaction,
        acquired: AuthorityId::SocketTopology,
    },
    CoholdRule {
        held: AuthorityId::ManagerTransaction,
        acquired: AuthorityId::SocketAssociation,
    },
    CoholdRule {
        held: AuthorityId::ManagerTransaction,
        acquired: AuthorityId::SocketDescriptor,
    },
    CoholdRule {
        held: AuthorityId::ManagerTransaction,
        acquired: AuthorityId::SocketIo,
    },
    CoholdRule {
        held: AuthorityId::ManagerTransaction,
        acquired: AuthorityId::ProtocolTransmit,
    },
    CoholdRule {
        held: AuthorityId::ManagerTransaction,
        acquired: AuthorityId::SessionControl,
    },
    CoholdRule {
        held: AuthorityId::ManagerTransaction,
        acquired: AuthorityId::ProtocolReceive,
    },
    CoholdRule {
        held: AuthorityId::ManagerTransaction,
        acquired: AuthorityId::ReceiverClaim,
    },
    CoholdRule {
        held: AuthorityId::ManagerTransaction,
        acquired: AuthorityId::WaitCoordination,
    },
    CoholdRule {
        held: AuthorityId::ManagerTransaction,
        acquired: AuthorityId::Maintenance,
    },
    CoholdRule {
        held: AuthorityId::SocketTopology,
        acquired: AuthorityId::SocketAssociation,
    },
    CoholdRule {
        held: AuthorityId::SocketTopology,
        acquired: AuthorityId::SocketDescriptor,
    },
    CoholdRule {
        held: AuthorityId::SocketAssociation,
        acquired: AuthorityId::SocketDescriptor,
    },
    CoholdRule {
        held: AuthorityId::SocketAssociation,
        acquired: AuthorityId::SocketAssociation,
    },
    CoholdRule {
        held: AuthorityId::SocketAssociation,
        acquired: AuthorityId::WaitCoordination,
    },
    CoholdRule {
        held: AuthorityId::SocketTopology,
        acquired: AuthorityId::WaitCoordination,
    },
    CoholdRule {
        held: AuthorityId::SocketTopology,
        acquired: AuthorityId::SocketIo,
    },
    CoholdRule {
        held: AuthorityId::SocketTopology,
        acquired: AuthorityId::SocketTopology,
    },
    CoholdRule {
        held: AuthorityId::SocketTopology,
        acquired: AuthorityId::ProtocolTransmit,
    },
    CoholdRule {
        held: AuthorityId::SocketTopology,
        acquired: AuthorityId::ManagerState,
    },
    CoholdRule {
        held: AuthorityId::SocketTopology,
        acquired: AuthorityId::SessionControl,
    },
    CoholdRule {
        held: AuthorityId::SocketTopology,
        acquired: AuthorityId::ProtocolReceive,
    },
    CoholdRule {
        held: AuthorityId::SocketTopology,
        acquired: AuthorityId::ReceiverClaim,
    },
    CoholdRule {
        held: AuthorityId::SocketTopology,
        acquired: AuthorityId::Maintenance,
    },
    CoholdRule {
        held: AuthorityId::ManagerState,
        acquired: AuthorityId::ManagerState,
    },
    CoholdRule {
        held: AuthorityId::ManagerState,
        acquired: AuthorityId::ReceiverClaim,
    },
];

pub(crate) const WAIT_RECORDS: &[WaitRecord] = &[
    WaitRecord {
        id: WaitId::FlowReadersDrain,
        retained: Some(AuthorityId::FlowWrite),
        bounded: true,
        shutdown_wake: true,
        waker: "flow reader release",
    },
    WaitRecord {
        id: WaitId::SocketIoDrain,
        retained: Some(AuthorityId::SocketTopology),
        bounded: true,
        shutdown_wake: true,
        waker: "socket I/O lane release",
    },
    WaitRecord {
        id: WaitId::SocketTopologyPublication,
        retained: None,
        bounded: true,
        shutdown_wake: true,
        waker: "socket topology commit or rollback",
    },
    WaitRecord {
        id: WaitId::FifoReservation,
        retained: None,
        bounded: true,
        shutdown_wake: true,
        waker: "reservation commit, rollback, or cancellation",
    },
    WaitRecord {
        id: WaitId::SupervisorTerminal,
        retained: None,
        bounded: true,
        shutdown_wake: true,
        waker: "thread terminal outcome",
    },
    WaitRecord {
        id: WaitId::StatsFinalMarkers,
        retained: None,
        bounded: true,
        shutdown_wake: true,
        waker: "producer FIFO marker",
    },
    WaitRecord {
        id: WaitId::DescriptorRevocation,
        // The topology reservation's closed gate is the wait authority. Its
        // dynamic co-hold scope is parked before this wait so a multi-socket
        // transaction never blocks while retaining one ranked instance.
        retained: None,
        bounded: true,
        shutdown_wake: true,
        waker: "socket I/O lane release grants closed-gate descriptor-cache clear ownership",
    },
];

pub(crate) const WAIT_PROTOCOL_RECORDS: &[WaitProtocolRecord] = &[
    WaitProtocolRecord {
        wait: WaitId::FlowReadersDrain,
        owner: TypeIdentity::FlowTopologyCoordinator,
        predicate_read: FunctionIdentity::FlowCloseAndDrain,
        waiter_registration: FunctionIdentity::FlowCloseAndDrain,
        post_registration_recheck: FunctionIdentity::FlowCloseAndDrain,
        notification: FunctionIdentity::FlowReaderRelease,
        cancellation: FunctionIdentity::FlowCloseAndDrain,
        teardown: FunctionIdentity::FlowCloseAndDrain,
        loom_invariant: InvariantId::FlowReaderDrain,
    },
    WaitProtocolRecord {
        wait: WaitId::SocketIoDrain,
        owner: TypeIdentity::ManagedSocket,
        predicate_read: FunctionIdentity::SocketCloseAndDrain,
        waiter_registration: FunctionIdentity::SocketCloseAndDrain,
        post_registration_recheck: FunctionIdentity::SocketCloseAndDrain,
        notification: FunctionIdentity::SocketIoRelease,
        cancellation: FunctionIdentity::SocketCloseAndDrain,
        teardown: FunctionIdentity::SocketCloseAndDrain,
        loom_invariant: InvariantId::SocketIoDrain,
    },
    WaitProtocolRecord {
        wait: WaitId::SocketTopologyPublication,
        owner: TypeIdentity::GroupPublicationTransaction,
        predicate_read: FunctionIdentity::GroupPublishCommitted,
        waiter_registration: FunctionIdentity::GroupPublishCommitted,
        post_registration_recheck: FunctionIdentity::GroupPublishCommitted,
        notification: FunctionIdentity::GroupPublishCommitted,
        cancellation: FunctionIdentity::GroupPoison,
        teardown: FunctionIdentity::GroupPoison,
        loom_invariant: InvariantId::GroupPublication,
    },
    WaitProtocolRecord {
        wait: WaitId::FifoReservation,
        owner: TypeIdentity::FifoReservationCore,
        predicate_read: FunctionIdentity::ReservationAllocate,
        waiter_registration: FunctionIdentity::ReservationAllocate,
        post_registration_recheck: FunctionIdentity::ReservationAllocate,
        notification: FunctionIdentity::ReservationRelease,
        cancellation: FunctionIdentity::ReservationCancel,
        teardown: FunctionIdentity::ReservationDrop,
        loom_invariant: InvariantId::FifoReservation,
    },
    WaitProtocolRecord {
        wait: WaitId::SupervisorTerminal,
        owner: TypeIdentity::RuntimeSupervisor,
        predicate_read: FunctionIdentity::WorkerTerminationComplete,
        waiter_registration: FunctionIdentity::SupervisorEnforceDeadline,
        post_registration_recheck: FunctionIdentity::SupervisorEnforceDeadline,
        notification: FunctionIdentity::WorkerTerminationComplete,
        cancellation: FunctionIdentity::ShutdownPublishFatal,
        teardown: FunctionIdentity::SupervisorEnforceDeadline,
        loom_invariant: InvariantId::ThreadOutcomePublication,
    },
    WaitProtocolRecord {
        wait: WaitId::StatsFinalMarkers,
        owner: TypeIdentity::StatsFinalityCore,
        predicate_read: FunctionIdentity::StatsAcknowledge,
        waiter_registration: FunctionIdentity::StatsBeginSealing,
        post_registration_recheck: FunctionIdentity::StatsAcceptNext,
        notification: FunctionIdentity::StatsQueuePublication,
        cancellation: FunctionIdentity::StatsAbandon,
        teardown: FunctionIdentity::StatsFinishSealing,
        loom_invariant: InvariantId::StatsFinality,
    },
    WaitProtocolRecord {
        wait: WaitId::DescriptorRevocation,
        owner: TypeIdentity::ManagedSocketInner,
        predicate_read: FunctionIdentity::DescriptorRequestRevocation,
        waiter_registration: FunctionIdentity::DescriptorRequestRevocation,
        post_registration_recheck: FunctionIdentity::DescriptorRequestRevocation,
        notification: FunctionIdentity::DescriptorAcknowledgeRevocation,
        cancellation: FunctionIdentity::DescriptorRequestRevocation,
        teardown: FunctionIdentity::DescriptorAcknowledgeRevocation,
        loom_invariant: InvariantId::DescriptorRevocation,
    },
];

pub(crate) const PUBLICATION_RECORDS: &[PublicationRecord] = &[
    PublicationRecord {
        id: PublicationId::FlowGateSnapshot,
        linearization: "open flow gate at the installed snapshot epoch",
        ordering: "AcqRel CAS-owned lane handshake; Release publication; Acquire observation",
        overflow: "checked epoch exhaustion is fatal before publication",
        aba_prevention: "every reopen, including rollback, advances the epoch",
        shutdown_interaction: "shutdown wakes the bounded reader drain",
        rollback_advances_epoch: true,
        stale_rejected: true,
    },
    PublicationRecord {
        id: PublicationId::SocketGateAssociation,
        linearization: "open socket gate at the published association epoch",
        ordering: "AcqRel CAS-owned lane handshake; Release publication; Acquire observation",
        overflow: "checked association epoch exhaustion is fatal",
        aba_prevention: "success and reversible rollback publish a fresh epoch",
        shutdown_interaction: "fatal drain timeout leaves the gate closed",
        rollback_advances_epoch: true,
        stale_rejected: true,
    },
    PublicationRecord {
        id: PublicationId::ReceiverGeneration,
        linearization: "Release store after receiver-slot publication",
        ordering: "Release/Acquire",
        overflow: "checked generation exhaustion rejects publication",
        aba_prevention: "receiver generations are monotonic and never reused",
        shutdown_interaction: "owner loss publishes fatal shutdown",
        rollback_advances_epoch: false,
        stale_rejected: true,
    },
    PublicationRecord {
        id: PublicationId::DescriptorGeneration,
        linearization: "closed-gate lane-cache clear before owner retirement; replacement identity publishes before gate reopen",
        ordering: "AcqRel CAS-owned gate drain; Release/Acquire replacement publication",
        overflow: "descriptor generation exhaustion fails before replacement publication",
        aba_prevention: "revocation acknowledgement precedes owner retirement and generation reuse is forbidden",
        shutdown_interaction: "revocation timeout is fatal and leaves the gate closed",
        rollback_advances_epoch: true,
        stale_rejected: true,
    },
    PublicationRecord {
        id: PublicationId::TransmitSequence,
        linearization: "allocation-status CAS reserves the sequence; the data bitmap separately marks in-flight before send",
        ordering: "AcqRel/Acquire",
        overflow: "sequence 65535 transitions to Exhausted without wrapping",
        aba_prevention: "one SessionId owns one non-circular sequence space",
        shutdown_interaction: "retirement rejects later reservations",
        rollback_advances_epoch: false,
        stale_rejected: true,
    },
    PublicationRecord {
        id: PublicationId::ActivityLane,
        linearization: "even seqlock publication",
        ordering: "Release/Acquire",
        overflow: "checked publication-sequence exhaustion is fatal",
        aba_prevention: "flow epoch and unchanged even sequence bind the tick",
        shutdown_interaction: "shutdown may stop publication; this record proves tuple coherence only",
        rollback_advances_epoch: false,
        stale_rejected: true,
    },
    PublicationRecord {
        id: PublicationId::IdleTimeoutTransition,
        linearization: "post-drain current-epoch activity revalidation authorizes timeout commit",
        ordering: "tentative read; writer close and reader drain; coherent Acquire rescan; commit or cancellation",
        overflow: "gate, activity, or reservation exhaustion fails before timeout mutation",
        aba_prevention: "writer reservation binds revalidation to the closed flow epoch and cancellation reopens at a fresh epoch",
        shutdown_interaction: "shutdown wakes reservation and drain waiters and forbids timeout mutation",
        rollback_advances_epoch: true,
        stale_rejected: true,
    },
    PublicationRecord {
        id: PublicationId::ControlObservationLane,
        linearization: "single-writer generation and phase publication",
        ordering: "Release/Acquire",
        overflow: "checked observation generation exhaustion is fatal",
        aba_prevention: "generation prevents lane reuse and the complete transaction key is published coherently for exact consumers",
        shutdown_interaction: "shutdown clears no authority and blocks mutation",
        rollback_advances_epoch: false,
        stale_rejected: true,
    },
    PublicationRecord {
        id: PublicationId::WakeGeneration,
        linearization: "single encoded generation-plus-pending CAS",
        ordering: "AcqRel CAS publication/clear with Acquire stability recheck",
        overflow: "checked wake-generation exhaustion is fatal",
        aba_prevention: "clear preserves generation and exact-state recheck prevents lost wake reuse",
        shutdown_interaction: "shutdown directly notifies every wait authority",
        rollback_advances_epoch: false,
        stale_rejected: true,
    },
    PublicationRecord {
        id: PublicationId::ShutdownState,
        linearization: "FatalPublished Release CAS/store",
        ordering: "Release/Acquire",
        overflow: "bounded owner encoding is validated before publication",
        aba_prevention: "fatal is terminal and graceful may only upgrade to fatal",
        shutdown_interaction: "publication wakes all nonblocking registered waiters",
        rollback_advances_epoch: false,
        stale_rejected: true,
    },
    PublicationRecord {
        id: PublicationId::StatsProducerLifecycle,
        linearization: "Sealed Release publication after FIFO marker",
        ordering: "Release/Acquire",
        overflow: "checked sequence/generation exhaustion marks final flush incomplete",
        aba_prevention: "one consuming seal generation per producer lifecycle",
        shutdown_interaction: "final marker retries only through the shared deadline",
        rollback_advances_epoch: false,
        stale_rejected: true,
    },
    PublicationRecord {
        id: PublicationId::ReservationOwnership,
        linearization: "owner-ticket CAS after FIFO serving-ticket admission",
        ordering: "AcqRel/Acquire",
        overflow: "ticket and cancellation-ring exhaustion fail before reuse",
        aba_prevention: "monotonic tickets and exact owner comparison",
        shutdown_interaction: "shutdown cancels the exact waiting ticket and wakes waiters",
        rollback_advances_epoch: false,
        stale_rejected: true,
    },
    PublicationRecord {
        id: PublicationId::ThreadOutcome,
        linearization: "outcome Ready Release publication after bounded cause storage",
        ordering: "Release/Acquire",
        overflow: "fixed preallocated slot count is checked before spawn",
        aba_prevention: "single-writer role slots never return to Empty",
        shutdown_interaction: "fatal cause is visible before terminal cleanup completes",
        rollback_advances_epoch: false,
        stale_rejected: true,
    },
    PublicationRecord {
        id: PublicationId::StatsNotification,
        linearization: "checked ready generation followed by pending false-to-true publication",
        ordering: "Release pending clear; AcqRel ownership claim; Acquire generation recheck",
        overflow: "ready-generation exhaustion publishes fatal shutdown",
        aba_prevention: "drain/clear/recheck compares the observed generation",
        shutdown_interaction: "50 ms scan remains a fallback when hint delivery fails",
        rollback_advances_epoch: false,
        stale_rejected: true,
    },
    PublicationRecord {
        id: PublicationId::MaintenanceDeadline,
        linearization: "repair owner publishes authoritative epoch before deadline hint",
        ordering: "Release/Acquire",
        overflow: "deadline-tick and maintenance-epoch overflow are typed fatal",
        aba_prevention: "repair owner and authoritative epoch reject stale clears",
        shutdown_interaction: "wake failure remains bounded by the poll fallback",
        rollback_advances_epoch: false,
        stale_rejected: true,
    },
    PublicationRecord {
        id: PublicationId::ListenerReplacement,
        linearization: "complete descriptor, association, manager version, and receiver publication before gate reopen",
        ordering: "closed AcqRel CAS-owned topology gate; Release/Acquire publication",
        overflow: "every component prechecks its generation/version capacity",
        aba_prevention: "old owner retirement and fresh topology epoch precede reopen",
        shutdown_interaction: "post-retirement failure poisons and remains fail-closed",
        rollback_advances_epoch: true,
        stale_rejected: true,
    },
];
