"""Authoritative semantic deadlines for Alpine and CI process orchestration."""

DOCKER_CONTROL_TIMEOUT_SECONDS = 15.0
DOCKER_PROFILE_TIMEOUT_SECONDS = 45.0
DOCKER_REALITY_PROFILE_TIMEOUT_SECONDS = 60.0
DOCKER_EXACT_TEST_TIMEOUT_SECONDS = 12.0
DOCKER_SUITE_TIMEOUT_SECONDS = 40.0
DOCKER_TEARDOWN_TIMEOUT_SECONDS = 15.0
ARTIFACT_BUILD_TIMEOUT_SECONDS = 15.0 * 60.0
VERIFIER_TIMEOUT_SECONDS = 2.0
TOPOLOGY_EVENT_TIMEOUT_SECONDS = 12.0
COMMAND_TERMINATION_GRACE_SECONDS = 0.5
EVENT_POLL_SECONDS = 0.1
FLOW_REPLY_TIMEOUT_SECONDS = 1.0
FLOW_RETRY_SECONDS = 0.2
FORWARDER_NODE_TIMEOUT_SECONDS = 20
HANDSHAKE_TIMEOUT_SECONDS = 2
